#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env.local}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — Google Calendar integration (spec 2026-09-05 §2.13, §6).
#
# Produces GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET and GCAL_TOKEN_KEY: written
# to .env.local for `npm run dev`, and (optionally) to the Vercel project's
# Production environment. Nothing goes to GitHub Actions — CI builds with
# placeholders and the feature is env-gated. Re-runnable: every prompt
# offers the value already in .env.local.
#
#   bash scripts/setup-google-calendar.sh
# ──────────────────────────────────────────────────────────────────────────

ENV_FILE=".env.local"
TEST_URL="https://booklo-five.vercel.app"
LOCAL_URL="http://localhost:3000"

# vercel_env NAME VALUE [--sensitive] — upsert a Production env var. The value
# goes through stdin, never argv, so it never shows in `ps`
# (setup-test-env.sh idiom).
vercel_env() {
  local name="$1" value="$2" flag="${3:-}"
  # shellcheck disable=SC2086
  if printf '%s' "$value" | vercel env add "$name" production --force --yes $flag >/dev/null 2>&1; then
    printf '  %s✓ vercel%s %s (production)\n' "$GREEN" "$RESET" "$name"
  else
    SKIPPED+=("Vercel env $name — set it in Settings → Environment Variables")
    warn "vercel env add $name failed — set it by hand later"
  fi
}

TOTAL_STAGES=6

banner "Google Calendar setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud — a project"
say "Booklo talks to Google Calendar through a Google Cloud project you own."
say "Reuse an existing one if you have it; otherwise create one (free)."
open_url "https://console.cloud.google.com/projectcreate"
step "Project name: Booklo (anything works). Leave the organisation as is. Create."
step "Wait for the notification, then make sure that project is SELECTED in the top bar."
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud — enable the Calendar API"
say "The project needs the Google Calendar API switched on."
open_url "https://console.cloud.google.com/apis/library/calendar-json.googleapis.com"
step "Check the selected project in the top bar, then click Enable."
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud — consent screen and test users"
say "What people see when they connect, and who is allowed to while the app"
say "is unverified. The calendar.events scope is 'sensitive': until Google"
say "verifies the app it stays in Testing, where up to 100 named test users"
say "can connect. Verification is a launch-checklist item, not needed today."
open_url "https://console.cloud.google.com/auth/overview"
step "If it says 'Get started': App name = Booklo, support email = yours,"
step "  Audience = External, contact email = yours. Agree, Create."
step "Then open Audience (left menu) → under Test users click 'Add users' and"
step "  add every Google account that will connect (yours first). Save."
step "(Branding: you can add the logo and links later — not needed for testing.)"
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud — the OAuth client"
say "The client ID/secret pair Booklo signs its requests with. One client can"
say "carry every environment's redirect URI, so register all three now."
open_url "https://console.cloud.google.com/auth/clients/create"
step "Application type: Web application. Name: Booklo web."
step "Authorised redirect URIs — add each one exactly:"
step "    ${LOCAL_URL}/api/google/callback"
step "    ${TEST_URL}/api/google/callback"
step "    https://<your production domain>/api/google/callback   (when you have one)"
step "Create. A dialog shows the Client ID and Client secret — copy both."
step "(The secret is shown ONCE here; you can download the JSON as a backup.)"
ask GOOGLE_CLIENT_ID "Paste the Client ID (ends with .apps.googleusercontent.com):"
ask_secret GOOGLE_CLIENT_SECRET "Paste the Client secret:"
write_env GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
write_env GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Token key"
say "Stored Google tokens are sealed with a key only the server holds."
say "Generated here, never typed. Keep it forever: rotating it orphans every"
say "connection (they show as needing a reconnect)."
GCAL_TOKEN_KEY=$(_existing GCAL_TOKEN_KEY || true)
if [[ -n "$GCAL_TOKEN_KEY" ]]; then
  note "keeping the key already in $ENV_FILE"
else
  GCAL_TOKEN_KEY=$(openssl rand -base64 32)
  note "generated a new 32-byte key"
fi
write_env GCAL_TOKEN_KEY "$GCAL_TOKEN_KEY"
say ""
say "Local dev is ready: restart 'npm run dev', open /integrations, Connect."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Vercel — production environment"
say "The same three values on the Vercel project, so the test/prod site can"
say "connect too. The client ID and secret can be the same client as local;"
say "the token key should be ITS OWN (a leaked local .env must not unlock"
say "production tokens) — so a fresh one is generated unless you say otherwise."
if command -v vercel >/dev/null 2>&1 && [[ -f .vercel/project.json ]]; then
  if confirm "Write GOOGLE_CLIENT_ID / GOOGLE_CLIENT_SECRET / GCAL_TOKEN_KEY to Vercel production now"; then
    PROD_KEY=$(openssl rand -base64 32)
    if confirm "Use the SAME token key as local instead of a fresh one (not recommended)"; then PROD_KEY="$GCAL_TOKEN_KEY"; fi
    vercel_env GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
    vercel_env GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET" --sensitive
    vercel_env GCAL_TOKEN_KEY "$PROD_KEY" --sensitive
    note "redeploy (or push to main) for the new values to take effect"
  else
    SKIPPED+=("Vercel env GOOGLE_CLIENT_ID / GOOGLE_CLIENT_SECRET / GCAL_TOKEN_KEY (Settings → Environment Variables)")
  fi
else
  SKIPPED+=("Vercel env vars — no vercel CLI or .vercel/project.json here; set them in Settings → Environment Variables")
fi

finish
