#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

# ── Fixed facts (verified 2026-08-26) ─────────────────────────────────────
REF="fkxtjtgwzwhwugxchuxo"                          # Supabase project "Booklo-prod", Frankfurt
SUPA_URL="https://${REF}.supabase.co"
TEST_URL="https://booklo-five.vercel.app"           # Vercel project "booklo" production domain
VERCEL_TEAM_SLUG="shcherbyakdevs-projects"
ENV_FILE=".env.test-env.local"                      # gitignored (.env*); NOT auto-loaded by Next (it only reads .env, .env.local, .env.<mode>[.local])

# vercel_env NAME VALUE [--sensitive] — upsert a Production env var. The value
# goes through stdin, never argv, so it never shows in `ps`.
vercel_env() {
  local name="$1" value="$2" flag="${3:-}"
  # shellcheck disable=SC2086
  if printf '%s' "$value" | vercel env add "$name" production --force --yes $flag >/dev/null 2>&1; then
    printf '  %s✓ vercel%s %s (production)\n' "$GREEN" "$RESET" "$name"
  else
    SKIPPED+=("Vercel env $name — set it in Settings → Environment Variables")
    warn "vercel env add $name failed — set it by hand later"
  fi
}

# ── Preflight: everything the stages assume ───────────────────────────────
preflight() {
  local ok=1
  [[ -f package.json && -f .vercel/project.json ]] || { warn "run me from the repo root (needs .vercel/project.json)"; ok=0; }
  for bin in vercel supabase npx curl openssl; do
    command -v "$bin" >/dev/null 2>&1 || { warn "missing: $bin"; ok=0; }
  done
  vercel whoami >/dev/null 2>&1 || { warn "Vercel CLI not logged in — run: vercel login"; ok=0; }
  supabase projects list 2>/dev/null | grep -q "$REF" || { warn "Supabase CLI not logged in — run: supabase login"; ok=0; }
  grep -q "site_url = \"$TEST_URL\"" supabase/config.toml || { warn "supabase/config.toml [remotes.production.auth].site_url is not $TEST_URL"; ok=0; }
  (( ok )) || { printf '\n'; exit 1; }
}
preflight

banner "Booklo — test environment on Vercel (${TEST_URL})"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Vercel — confirm the test URL is reachable without a Vercel login"
say "Deployment Protection is 'All except custom domains' on this project. Verified"
say "2026-08-26: that leaves the project's own ${TEST_URL} public and walls only"
say "per-deployment / preview URLs — which is what a shareable test env wants."
code=$(curl -sS -o /dev/null -w '%{http_code}' "$TEST_URL/" || echo "000")
if [[ "$code" == "200" || "$code" == "404" ]]; then
  printf '  %s✓ %s answers %s without a login%s\n' "$GREEN" "$TEST_URL" "$code" "$RESET"
  note "(404 is fine before the first deploy.)"
else
  warn "$TEST_URL answered $code — if that is a redirect to vercel.com/login, relax the setting:"
  open_url "https://vercel.com/${VERCEL_TEAM_SLUG}/booklo/settings/deployment-protection"
  step "Vercel Authentication → 'Only Preview Deployments' → Save."
  confirm "Done?" || SKIPPED+=("Deployment Protection → Vercel Authentication → Only Preview Deployments")
fi
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Supabase — API keys"
open_url "https://supabase.com/dashboard/project/${REF}/settings/api-keys"
step "Copy the Publishable key (sb_publishable_…)."
ask NEXT_PUBLIC_SUPABASE_ANON_KEY "Paste the publishable key:"
[[ "$NEXT_PUBLIC_SUPABASE_ANON_KEY" == sb_publishable_* || "$NEXT_PUBLIC_SUPABASE_ANON_KEY" == eyJ* ]] || warn "doesn't look like a publishable (sb_publishable_…) or legacy anon (eyJ…) key"
step "Copy the Secret key (sb_secret_…) — click Reveal first."
ask_secret SUPABASE_SERVICE_ROLE_KEY "Paste the secret key:"
[[ "$SUPABASE_SERVICE_ROLE_KEY" == sb_secret_* || "$SUPABASE_SERVICE_ROLE_KEY" == eyJ* ]] || warn "doesn't look like a secret (sb_secret_…) or legacy service_role (eyJ…) key"
write_env NEXT_PUBLIC_SUPABASE_URL "$SUPA_URL"
write_env NEXT_PUBLIC_SUPABASE_ANON_KEY "$NEXT_PUBLIC_SUPABASE_ANON_KEY"
write_env SUPABASE_SERVICE_ROLE_KEY "$SUPABASE_SERVICE_ROLE_KEY"
vercel_env NEXT_PUBLIC_SUPABASE_URL "$SUPA_URL"
vercel_env NEXT_PUBLIC_SUPABASE_ANON_KEY "$NEXT_PUBLIC_SUPABASE_ANON_KEY"
vercel_env SUPABASE_SERVICE_ROLE_KEY "$SUPABASE_SERVICE_ROLE_KEY" --sensitive

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Supabase — the two pooler connection strings"
say "Production uses TWO different DATABASE_URLs on purpose:"
say "  transaction pooler :6543 → Vercel runtime"
say "  session pooler     :5432 → migrations (DDL) from this laptop / GitHub"
note "Both need the database password. Lost it? Reset at"
note "https://supabase.com/dashboard/project/${REF}/settings/database (Reset database password)."
note "If the password has @ : / # or % in it, URL-encode it inside the URI."
open_url "https://supabase.com/dashboard/project/${REF}?showConnect=true"
step "Connect → Connection string → Method: Transaction pooler → copy the URI,"
step "replace [YOUR-PASSWORD] with the real password."
while :; do
  ask_secret DATABASE_URL_TRANSACTION "Paste the TRANSACTION pooler URI (:6543):"
  [[ "$DATABASE_URL_TRANSACTION" == *pooler.supabase.com:6543* && "$DATABASE_URL_TRANSACTION" != *"[YOUR-PASSWORD]"* ]] && break
  warn "expected …pooler.supabase.com:6543 with the real password substituted — try again"
done
step "Now Method: Session pooler → copy the URI, replace [YOUR-PASSWORD]."
while :; do
  ask_secret DATABASE_URL_SESSION "Paste the SESSION pooler URI (:5432):"
  [[ "$DATABASE_URL_SESSION" == *pooler.supabase.com:5432* && "$DATABASE_URL_SESSION" != *"[YOUR-PASSWORD]"* ]] && break
  warn "expected …pooler.supabase.com:5432 with the real password substituted — try again"
done
write_env DATABASE_URL_TRANSACTION "$DATABASE_URL_TRANSACTION"
write_env DATABASE_URL_SESSION "$DATABASE_URL_SESSION"
vercel_env DATABASE_URL "$DATABASE_URL_TRANSACTION" --sensitive

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Resend — API key"
say "Needed twice: the app sends mail through Resend, and Supabase Auth's SMTP"
say "(pushed in stage 6) uses the same key. Without SMTP, Supabase only delivers"
say "auth mail to YOUR address — nobody else could sign up on the test env."
open_url "https://resend.com/api-keys"
step "Use an existing key you still have, or 'Create API Key' (Full access)."
note "Keys are shown once, at creation."
while :; do
  ask_secret RESEND_API_KEY "Paste the Resend API key (re_…):"
  [[ "$RESEND_API_KEY" == re_* ]] && break
  warn "Resend keys start with re_ — try again"
done
write_env RESEND_API_KEY "$RESEND_API_KEY"
vercel_env RESEND_API_KEY "$RESEND_API_KEY" --sensitive
vercel_env EMAIL_FROM "Booklo <noreply@booklo.co>"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "App settings — generated secrets and fixed values"
SCHEDULING_DRAIN_SECRET=$(_existing SCHEDULING_DRAIN_SECRET || openssl rand -hex 24)
CHASE_DRAIN_SECRET=$(_existing CHASE_DRAIN_SECRET || openssl rand -hex 24)
say "Drain secrets generated (kept in ${ENV_FILE} so you can tick reminders by hand)."
ask INTERNAL_EMAILS "Emails allowed into /utils (comma-separated) [andriishcherbiakdev@gmail.com,andriyshcherbyak@gmail.com]:"
INTERNAL_EMAILS="${INTERNAL_EMAILS:-andriishcherbiakdev@gmail.com,andriyshcherbyak@gmail.com}"
write_env SCHEDULING_DRAIN_SECRET "$SCHEDULING_DRAIN_SECRET"
write_env CHASE_DRAIN_SECRET "$CHASE_DRAIN_SECRET"
write_env INTERNAL_EMAILS "$INTERNAL_EMAILS"
vercel_env APP_ENV "production"
vercel_env NEXT_PUBLIC_APP_URL "$TEST_URL"
vercel_env SCHEDULING_DRAIN_SECRET "$SCHEDULING_DRAIN_SECRET" --sensitive
vercel_env CHASE_DRAIN_SECRET "$CHASE_DRAIN_SECRET" --sensitive
vercel_env INTERNAL_EMAILS "$INTERNAL_EMAILS"
note "(BILLING_FAKE_SECRET deliberately NOT set: src/env-schema.ts rejects it under APP_ENV=production.)"
printf '\n'; vercel env ls production 2>/dev/null | sed 's/^/  /' || true
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Supabase — push auth config (site_url, redirects, SMTP, rate limits, templates)"
say "Pushes supabase/config.toml's [remotes.production] block to ${REF}."
warn "Overwrites the project's remote config. Review the diff the CLI shows — it covers"
warn "API/DB/storage too, not just auth — and answer its prompt."
if confirm "Push now?"; then
  out=$(mktemp)
  if RESEND_API_KEY="$RESEND_API_KEY" supabase config push --project-ref "$REF" 2>&1 | tee "$out"; then
    if grep -q "Loading config override" "$out"; then
      printf '  %s✓ override applied%s (saw "Loading config override")\n' "$GREEN" "$RESET"
    else
      warn "'Loading config override' NOT in the output — the CLI pushed the BASE (localhost) config."
      SKIPPED+=("config push applied the base config, not [remotes.production] — investigate before deploying")
    fi
  else
    SKIPPED+=("supabase config push (declined or failed)")
  fi
  rm -f "$out"
else
  SKIPPED+=("supabase config push --project-ref $REF")
fi
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Database — apply migrations (session pooler)"
say "ALLOW_REMOTE_DB=1 DATABASE_URL=<session :5432> npx drizzle-kit migrate"
note "Idempotent: drizzle's journal skips what is already applied."
if confirm "Migrate ${REF} now?"; then
  if ALLOW_REMOTE_DB=1 DATABASE_URL="$DATABASE_URL_SESSION" npx drizzle-kit migrate; then
    printf '  %s✓ migrated%s\n' "$GREEN" "$RESET"
  else
    SKIPPED+=("drizzle-kit migrate failed — check the pooler URL/password")
  fi
else
  SKIPPED+=("drizzle-kit migrate")
fi
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Vercel — first production deploy (from this laptop)"
say "vercel deploy --prod  (source upload; Vercel builds in its cloud)"
note "NOT the prebuilt flow from deploy.yml: this team stores every env var as"
note "Sensitive (write-only), so 'vercel pull' returns placeholders and a local"
note "'vercel build' fails env validation. Cloud builds see the real values."
note ".vercelignore keeps .claude/worktrees, docs, graphify-out etc. out of the upload."
if confirm "Deploy now? (takes a few minutes)"; then
  if vercel deploy --prod --yes; then
    printf '\n'
    if curl -fsS "$TEST_URL/" >/dev/null; then
      printf '  %s✓ %s answers%s\n' "$GREEN" "$TEST_URL" "$RESET"
    else
      warn "$TEST_URL did not answer 200 — if it redirects to vercel.com/login, stage 1 was not applied"
    fi
    status=$(curl -sS -o /dev/null -w '%{http_code}' -X POST "$TEST_URL/api/scheduling/drain" || echo "000")
    if [[ "$status" == "401" ]]; then
      printf '  %s✓ drain route rejects anonymous calls (401) — SCHEDULING_DRAIN_SECRET is live%s\n' "$GREEN" "$RESET"
    else
      warn "POST /api/scheduling/drain returned $status (expected 401; 503 means the secret is missing)"
    fi
  else
    SKIPPED+=("deploy failed — rerun: vercel deploy --prod --yes")
  fi
else
  SKIPPED+=("first deploy")
fi

finish
say "Smoke test (spec §12, minus domain items):"
step "Sign up at ${TEST_URL} from a NON-owner address — the only proof SMTP works; the link must point at ${TEST_URL}."
step "Finish onboarding; take a booking on the public page; check client + provider mail."
step "Sign in as the owner → ${TEST_URL}/utils (proves INTERNAL_EMAILS)."
step "Password reset end-to-end."
step "Reminders have no cron here — tick by hand:"
note "  SCHEDULING_DRAIN_SECRET=\$(grep ^SCHEDULING_DRAIN_SECRET= ${ENV_FILE} | cut -d= -f2-) npm run scheduling:drain -- --url ${TEST_URL}"
printf '\n'
